version: '3'

services:
  frontend:
    image: da9d2bf3a469
    build: .
    ports:
      - 5173:5173
    restart: always
  backend:
    image: 4215af604ec9
    build: .
    ports:
      - 3000:3000
    restart: always
