version: '3.7'

services:
  frontend:
    image: ltdthanhdat/hcfe:lastest
    build: .
    ports:
      - 5173:5173
    restart: always
  backend:
    image: ltdthanhdat/hcbe:lastest
    build: .
    ports:
      - 3000:3000
    restart: always
