version: '3'

services:
  frontend:
    image: c597423b1a98
    build: .
    ports:
      - 5173:5173
    restart: always
  backend:
    image: 496e868cb615
    build: .
    ports:
      - 3000:3000
    restart: always
